// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppController from "./app_controller"
application.register("app", AppController)

import MenuController from "./layouts/menu/menu_controller"
application.register("menu", MenuController)

import MenuMainController from "./layouts/menu/menu_main_controller"
application.register("menu-main", MenuMainController)
