:lograge:
  enabled: true
  keep_original: false
:mailer:
  :delivery_method:
  :address:
  :domain:
  :port:
  :enable_starttls_auto:
  :authentication:
  :user_name: # see ENV
  :password: # see ENV